### ISSUE TITLE
Request to use hostPath volumes on OF Zero cluster

### ISSUE THREAD

**Issue by phpHavok** [operate-first/support#201]
**Cluster**: OF Zero
**Team**: uky-redhat
**Project**: uky-hpc-workload-generator

**Description**

I have a unique application where I need to access the full /sys/fs/cgroup hierarchy (read-only is fine) from within a Docker container. Docker does usually expose /sys/fs/cgroup inside the container, but its usually a more trimmed down tree (not the full cgroup hierarchy which includes the cgroup that the container is actually running in). This is easy to fix because you can just do a volume read-only bind mount of the real /sys/fs/cgroup into the container (you will have read-only access on the parent machine that you're launching the container from). I.e.,

```
# Command tested and working:
docker run -t --rm \
    --mount type=bind,src=/sys/fs/cgroup,dst=/sys/fs/cgroup,readonly \
    --mount type=bind,src=`pwd`,dst=/data \
    phphavok/hpc-workload-generator -i /data/example.schedule
```

So, I need to do this inside a K8s environment. I got that working in minikube by using a volume mount with host path. I.e:

```
    spec:
      containers:
        - name: hpc-workload-generator
          image: phphavok/hpc-workload-generator
          args:
            - "-i"
            - "example.schedule"
          volumeMounts:
            - name: cgroup
              mountPath: /sys/fs/cgroup
      volumes:
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
```

However, while this works in my minikube environment, OF seems to disallow hostPath to be used:

```
reason: FailedCreatemessage: >-pods "hpc-workload-generator-5b9c8c45d5-" is forbidden: unable to validate against any security context constraint: [spec.volumes[0]:Invalid value: "hostPath": hostPath volumes are not allowed to be used]
```

Does anyone know a way around this, or can I be granted the permission to use hostPath?
