### ISSUE TITLE
Support for ACME's Let's Encrypt certificates registration for routes cluster-wide?

### ISSUE THREAD

**Issue by gastaldi** [operate-first/support#237]
**Description**
There is an [ACME Controller for OpenShift and Kubernetes clusters](https://github.com/tnozicka/openshift-acme) that automatically performs the process of requesting a valid certificate from [Let's Encrypt](https://letsencrypt.org/) to HTTP/S routes when the `kubernetes.io/tls-acme=true` annotation is added to the route. 

Are there any plans to make this service cluster-wide or the recommended approach is to install this service on each project on a demand basis?

**Comment by tumido** [comment]
Hey @gastaldi sorry for a late response. We certainly want to have that controller deployed. We've been thinking if this can be replaced with cert-manager operator but that seems it doesn't support OpenShift routes and OpenShift routes don't support loading certificates from secrets so we probably have no choice than deploy both to support providing certificates for different needs in different ways.

Reference: https://github.com/jetstack/cert-manager/issues/1064  https://github.com/openshift/origin/issues/2162

We're gonna deploy the cluster wide `openshift-acme` asap.

**Comment by tumido** [comment]
@gastaldi

**Comment by tumido** [comment]
Actually, we have to fix one more thing :facepalm: https://github.com/operate-first/apps/pull/645 one merged it should get deployed asap automatically.

**Comment by gastaldi** [comment]
@tumido thanks. It looks like the temporary routes are not being created? I see an error in my route:

```yaml
    acme.openshift.io/status: |
      provisioningStatus:
        earliestAttemptAt: "2021-05-13T16:29:36.170078253Z"
        failures: 5
        orderStatus: invalid
        orderURI: https://acme-v02.api.letsencrypt.org/acme/order/123394935/9673517895
        startedAt: "2021-05-13T16:29:36.170078253Z"
```
