### ISSUE TITLE
Deploy Google Spark operator

### ISSUE THREAD

**Issue by tumido** [operate-first/support#241]
### Requested actions

Recently we've seen a demand for Google Spark operator to be deployed on the cluster. 

https://github.com/operate-first/apps/pull/642#pullrequestreview-658728665

Users are trying to bring this operator in on there own at cluster scope - instead of hosting this operator in a user namespace we should fully test in and provide it from OPS managed namespace. @guimou has some nice samples that can help us properly onboard this to OpenShift.

#### Operator request

If you want to request an operator, please provide the following:

1. **Name of the Operator**: Spark Operator

2. **Operator version**: :shrug: 

3. **Operator scope**: Cluster scope

4. **Documentation and links**:  https://github.com/guimou/spark-on-openshift

**Comment by tumido** [comment]
Since the operator itself is deployed from help charts it may be useful for us to try to deploy it via ArgoCD's Helm application. But the end result PR should avoid Helm charts if possible, since we don't want to include remote locations outside of this org to manage cluster scoped resources.

**Comment by tumido** [comment]
Related: https://chat.google.com/room/AAAAiODw-Fc/XXTex4jzwQo

**Comment by HumairAK** [comment]
For additional reference these are the cluster rbac that's added from helm: 
<details> 
---

```yaml
# Source: spark-operator/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-operator
  labels:
    helm.sh/chart: spark-operator-1.1.0
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/instance: spark-operator
    app.kubernetes.io/version: "v1beta2-1.2.3-3.1.1"
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - services
  - configmaps
  - secrets
  verbs:
  - create
  - get
  - delete
  - update
- apiGroups:
  - extensions
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - get
  - delete
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - resourcequotas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - get
  - update
  - delete
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - create
  - get
  - update
  - delete
- apiGroups:
  - sparkoperator.k8s.io
  resources:
  - sparkapplications
  - sparkapplications/status
  - scheduledsparkapplications
  - scheduledsparkapplications/status
  verbs:
  - "*"
  
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - delete
---
# Source: spark-operator/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-operator
  labels:
    helm.sh/chart: spark-operator-1.1.0
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/instance: spark-operator
    app.kubernetes.io/version: "v1beta2-1.2.3-3.1.1"
    app.kubernetes.io/managed-by: Helm
subjects:
  - kind: ServiceAccount
    name: spark-operator
    namespace: spark-operator
roleRef:
  kind: ClusterRole
  name: spark-operator
  apiGroup: rbac.authorization.k8s.io
---
```
</details>

rest are namespace resources that would be delegated to a separate  app.

**Comment by HumairAK** [comment]
@guimou my understanding is that there is some prep you need to do before we should take this on, if you could bump this thread once it's ready we can go ahead and get this deployed

**Comment by HumairAK** [comment]
I think if the plan is for this to be incorporated in to odh, having an odh manifest to point a kfdef to would probably be ideal. Then we could present it as a live deployment of your working example for odh devs to check out. 

@tumido

**Comment by tumido** [comment]
I think if we can deploy it as an ODH component, even better and even easier for us. :+1: 

We can deploy from your repo if needed. It doesn't have to be included in the ODH for us to deploy it. But once it is, we should switch over. :slightly_smiling_face: 

We certainly prefer ODH components and `kfdefs` over Helm charts. :smile: Would you agree @HumairAK ?

**Comment by HumairAK** [comment]
> Would you agree @HumairAK ?
![image](https://user-images.githubusercontent.com/10904967/118157119-2a655280-b3e8-11eb-8fd7-e4aa678a65ca.png)

**Comment by tloubrieu-jpl** [comment]
Hello, do you have an estimation for the realization of this ticket ? It is a requirement for my deployment (see https://github.com/operate-first/support/issues/206) and I will need to report that to my project.

Thanks,

**Comment by guimou** [comment]
Well, I'll try to finalize something by the end of this week. But no
guarantees. Although that now you mention it's really waited after its
status in my work queue has improved... 😁

**Comment by tloubrieu-jpl** [comment]
Thanks @guimou, that works well, I was just asking since I had no ideas if the I should expect days, weeks or months, days is perfect time scale !

**Comment by tloubrieu-jpl** [comment]
Hi @guimou , any update on this ticket ? We need the spark operator for our deployment that is why I am contacting you again. 
Thanks

**Comment by guimou** [comment]
Things are mostly done, just not fully tested. If you want to give it a try... ;-)
- "Manual" instructions: https://github.com/guimou/spark-on-openshift
- Custom manifest for ODH (should make the PR today or tomorrow, I want to check some more things first): https://github.com/guimou/odh-manifests/tree/spark-operator/google-spark-operator

**Comment by HumairAK** [comment]
>  I want to check some more things first 

@guimou let us know when you've made your pr (I presume you are talking about odh-manifests repo), I think we can consider that ready to deploy on our cluster

**Comment by guimou** [comment]
@HumairAK Just did the PR for the spark-operator manifest: https://github.com/opendatahub-io/odh-manifests/pull/427

**Comment by HumairAK** [comment]
Okay thanks, I'll set up a kfdef

**Comment by HumairAK** [comment]
update: I deployed the kfdef but encountered some issues I've posted in the PR linked above: https://github.com/opendatahub-io/odh-manifests/pull/427#issuecomment-845991304

**Comment by tloubrieu-jpl** [comment]
Hello @HumairAK , @guimou , what would be the estimated time when the spark-operator could be actually available on operate-first cluster ? Thanks

**Comment by HumairAK** [comment]
@tloubrieu-jpl we have @guimou 's implementation for odh deployed, are you able to test it out? 

You may need to add additional rbac and a serviceaccount, see @guimou 's notes in his branch [here](https://github.com/guimou/odh-manifests/tree/spark-operator/google-spark-operator). If you face permission errors, please post them here and one of us or @guimou will try to help in resolving them.

**Comment by HumairAK** [comment]
@guimou I'm not up to date with the plans for this operator, I see that now it's slated to go to kubeflow first. It would be most appreciated if you could keep this thread in your mind, and update us if there's a better path forward for us to implement your solution, as you work on this.

**Comment by guimou** [comment]
It's a little bit more complicated. I'll try to submit a PR in Kubeflow to have them update the Spark operator that already exists but is based on an old version. If it's accepted quickly perfect. If this is rejected for whatever reason or takes too long we'll advise.
Meanwhile, people can still use my "instructions" on https://github.com/guimou/spark-on-openshift, or use the manifest from this branch https://github.com/guimou/odh-manifests/tree/spark-operator.

**Comment by 4n4nd** [comment]
> It's a little bit more complicated. I'll try to submit a PR in Kubeflow to have them update the Spark operator that already exists but is based on an old version. If it's accepted quickly perfect. If this is rejected for whatever reason or takes too long we'll advise.
> Meanwhile, people can still use my "instructions" on https://github.com/guimou/spark-on-openshift, or use the manifest from this branch https://github.com/guimou/odh-manifests/tree/spark-operator.

Cool, https://github.com/guimou/odh-manifests/tree/spark-operator is the branch that we have deployed. Once it is accepted upstream kubeflow, we can point the kfdef to upstream kubeflow. All we need someone to do is test our deployment.

**Comment by tloubrieu-jpl** [comment]
@HumairAK, @guimou , thanks for the deployment on operate-first. I will test it this week.

**Comment by tloubrieu-jpl** [comment]
@HumairAK @guimou , I have updated my deployment and tried to deploy it on operate-first, namespace sdap. But I am having an issue that I don't understand:

`% helm install sdap ./helm/  -f values-moc.yaml  -n sdap --dependency-update
Error: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource: sparkapplications.sparkoperator.k8s.io "nexus-webapp" is forbidden: User "loubrieu@jpl.caltech.edu" cannot get resource "sparkapplications" in API group "sparkoperator.k8s.io" in the namespace "sdap"`


I have pushed my updates to our deployment templates on this repo/branch : https://github.com/tloubrieu-jpl/incubator-sdap-nexus/tree/moc_deployment

The templates are in `helm/templates/`

Do you think this is an authorization issue or an issue with my template files ?

Thanks,

Thomas

**Comment by guimou** [comment]
@tloubrieu-jpl I don't see anything special in you files. Maybe more tied to your own rights in the cluster.
Have you tried just to create a basic standalone dummy Sparkapplication?

**Comment by tloubrieu-jpl** [comment]
Thanks @guimou
I tried to simplify my templates to only have the sparkapplication and the role, rolebinding and serviceaccount you required but that does not change the error message.

I noticed that the sparkapplication templates has a sparkVersion property equal 2.4.4 (see https://github.com/tloubrieu-jpl/incubator-sdap-nexus/blob/moc_deployment/helm/templates/webapp.yml). Would that work ?

Also if you have a pointer to guide me on how to create a dummy sparkapplication, I'll be happy to test that. Thanks.

**Comment by HumairAK** [comment]
@tloubrieu-jpl you should now have the ability to list/read/create sparkapplications

**Comment by tloubrieu-jpl** [comment]
Hi @guimou , @HumairAK 

I restested the deployment of our appliction using the spark operator.

I've added the role.yaml and the other requested files on https://github.com/guimou/odh-manifests/tree/spark-operator/google-spark-operator

But this gives an error:
Error: roles.rbac.authorization.k8s.io "sdap-spark-role" is forbidden: user "loubrieu@jpl.caltech.edu" (groups=["sdap-mslsp" "system:authenticated:oauth" "system:authenticated"]) is attempting to grant RBAC permissions not currently held:
{APIGroups:[""], Resources:["pods"], Verbs:["*"]}
{APIGroups:[""], Resources:["services"], Verbs:["*"]}

Here is the content of this file:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/instance: spark-operator
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/version: v1beta2-1.2.3-3.1.1
  name: sdap-spark-role
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - services`

```

I guess I should change the value in verbs but I don't know  what I should use.

Thanks
