### ISSUE TITLE
How to dispose your own (user) persistent volume claim

### ISSUE THREAD

**Issue by codificat** [operate-first/support#247]
**Is your feature request related to a problem? Please describe.**

I was trying to troubleshoot an issue (thoth-station/jupyterlab-requirements#269) and wanted to "start fresh", and I thought that a quick and reliable way to do that would include getting rid of my PVC and get a new empty PVC attached.

I could not find a way to do that, though.

**Describe the solution you'd like**

A simple documented process to dispose an existing PVC (probably to get a new one allocated).

**Describe alternatives you've considered**

Of course, one can `rm -rf $HOME`... but I thought I'd leave this feature suggestion.

**Additional context**

I was trying these nice and short videos on [how to deploy notebooks](https://youtu.be/iI_-lqi3vP4) and [manage their dependencies](https://youtu.be/ifyQ2oSxjnU).

**Comment by 4n4nd** [comment]
Is there any RBAC that we could add which gives a user access only to their own PVCs? 
@HumairAK @tumido

**Comment by tumido** [comment]
We can do something like this via RBAC. However this is kinda limited, as shown below.

This RBAC will allow users to get/delete their own PVC via ocp cli/UI:

```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jupyterhub-nb-XXX-pvc
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  resourceNames:
  - jupyterhub-nb-XXX-pvc
  verbs:
  - list
  - get
  - watch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name:  jupyterhub-nb-XXX-pvc
roleRef:
  kind: Role
  name:  jupyterhub-nb-XXX-pvc
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: XXX
  apiGroup: rbac.authorization.k8s.io
```

This results in users being able to get the pvc via CLI:

```
oc get persistentvolumeclaims/jupyterhub-nb-XXX-pvc
NAME                                           STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                AGE
jupyterhub-nb-XXX-pvc   Bound    pvc-bc07cbc7-1ce5-43ef-b71c-f0ff5077bfb4   2Gi        RWO            ocs-storagecluster-cephfs   13m
```
![image](https://user-images.githubusercontent.com/7453394/118832856-41f97b00-b8c1-11eb-8704-c0aa396dd5ec.png)


However users can get a list of PVCs without revealing the rest of PVCs available:
```
oc get persistentvolumeclaims
Error from server (Forbidden): persistentvolumeclaims is forbidden: User "XXX" cannot list resource "persistentvolumeclaims" in API group "" in the namespace "opf-jupyterhub"
```

![image](https://user-images.githubusercontent.com/7453394/118833036-6bb2a200-b8c1-11eb-85f4-edee4177acc9.png)


This makes the RBAC pretty pointless since user doesn't know where to find the PVC unless they know the exact name of the resource.

Further more granular control over PVC listing may be possible to achieve via OPA/Gatekeeper policy, but that would require quite a lot of work now. We may work on it down the road.

### Note 1
Adding
```yaml
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - list
```

To the role above would result in ability to list all the pvcs for all users potentially revealing usernames to every user with this role attach. 

### Note 2

There's currently no way to assign this RBAC dynamically, when user logs into JupyterHub on our end - it would have to either be per request, or deployed and managed by JupyterHub spawner. In ODH.

In the long run I think we should invest in deploying OPA/Gatekeeper so we can do this kind of dynamic stuff with RBAC and admission control etc .

Linking: https://github.com/operate-first/support/issues/248
