### ISSUE TITLE
Create a pretty URL for Pulp

### ISSUE THREAD

**Issue by fridex** [operate-first/support#278]
**Is your feature request related to a problem? Please describe.**

As user of Pulp, I would like to have easy access to a Pulp instance. To access Pulp easily, a pretty URL could be created.

**Describe the solution you'd like**

Create a pretty url for pulp. As of now, we use https://pulp.apps.zero.massopen.cloud/. Would it be possible to create a prettier URL? For example https://pulp.operate-first.cloud/

**Comment by fridex** [comment]
CC @ipanova @goern

**Comment by tumido** [comment]
Yes, it would be possible :slightly_smiling_face:

**Comment by tumido** [comment]
Something like this? https://pulp.operate-first.cloud/

**Comment by fridex** [comment]
> Something like this? https://pulp.operate-first.cloud/

Great! That was faster than I thought. 👍🏻 💯 

/close

**Comment by tumido** [comment]
@fridex I've created this route manually. If you track these experiments in git somewhere, I can make a PR:

https://console-openshift-console.apps.zero.massopen.cloud/k8s/ns/thoth-pulp-experiments/routes/external

```yaml
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: external
  namespace: thoth-pulp-experiments
  annotations:
    kubernetes.io/tls-acme: 'true'
spec:
  host: pulp.operate-first.cloud
  to:
    kind: Service
    name: example-pulp-web-svc
    weight: 100
  port:
    targetPort: web-8080
```
