### ISSUE TITLE
MIGRATE PROJECT:  thoth-test-core

### ISSUE THREAD

**Issue by goern** [operate-first/support#372]
### Target cluster

Rick

### Team name

aicoe-thoth

### Desired project names

thoth-test-core

### Project description

This is `thoth-test-core` and all it's dependencies being migrated from `zero` to `rick`

### Users needing access

same as on `zero`

### Namespace Quota

Custom

### Custom quota

```
status:
  hard:
    limits.cpu: "16"
    limits.memory: 32Gi
    requests.cpu: "16"
    requests.memory: 32Gi
    requests.storage: 40Gi
  used:
    limits.cpu: 8500m
    limits.memory: 12448Mi
    requests.cpu: 6875m
    requests.memory: 6080Mi
    requests.storage: 40Gi
```

# Acceptance Criteria
- [ ] all thoth-test-core components are up and running
- [ ] list of dependencies ist available at https://github.com/thoth-station/thoth-application/tree/master/docs
- [ ] op1st doc on how to migrate a namespace is available as part of https://github.com/operate-first/hitchhikers-guide
