### ISSUE TITLE
Have a way to view hardware and info from the nodes for users

### ISSUE THREAD

**Issue by pacospace** [operate-first/support#409]
**Is your feature request related to a problem? Please describe.**
As Data Scientist/Developer,

I want to deploy a model that requires a specific flag and hardware.

**Describe the solution you'd like**
I would like to have a way to check the view of hardware info on the nodes so that I can use this information for deployments. In this way, I could deploy the model using Node Feature Discovery (NFD).

**Describe alternatives you've considered**

**Additional context**
Related-To: https://github.com/operate-first/support/issues/408

**Comment by pacospace** [comment]
what about deploying a component that exposes `/proc/cpuinfo` to Prometheus and we can check grafana dashboard for that? Something similar to https://github.com/prometheus/procfs

**Comment by HumairAK** [comment]
related: https://github.com/operate-first/support/issues/324

**Comment by tumido** [comment]
So for baremetal clusters we can explore [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics) which will be included in OCP 4.9. This will allow us to query for `BareMetalHost` resources and observe the CPU flags:

```yaml
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
status:
  hardware:
    cpu:
     ...
      flags:
        - fpu
        - vme
        - de
        - pse
        - tsc
        - msr
        - pae
        - mce
        - cx8
        - apic
        - sep
        - mtrr
        - pge
        - mca
        - cmov
        - pat
        - pse36
        - clflush
        - dts
        - acpi
        - mmx
        - fxsr
        - sse
        - sse2
        - ss
        - ht
        - tm
        - pbe
        - syscall
        - nx
        - pdpe1gb
        - rdtscp
        - lm
        - constant_tsc
        - arch_perfmon
        - pebs
        - bts
        - rep_good
        - nopl
        - xtopology
        - nonstop_tsc
        - cpuid
        - aperfmperf
        - pni
        - pclmulqdq
        - dtes64
        - monitor
        - ds_cpl
        - vmx
        - smx
        - est
        - tm2
        - ssse3
        - cx16
        - xtpr
        - pdcm
        - pcid
        - dca
        - sse4_1
        - sse4_2
        - x2apic
        - popcnt
        - tsc_deadline_timer
        - aes
        - xsave
        - avx
        - f16c
        - rdrand
        - lahf_lm
        - cpuid_fault
        - pti
        - ssbd
        - ibrs
        - ibpb
        - stibp
        - tpr_shadow
        - vnmi
        - flexpriority
        - ept
        - vpid
        - fsgsbase
        - smep
        - erms
        - xsaveopt
        - dtherm
        - ida
        - arat
        - pln
        - pts
        - md_clear
        - flush_l1d
      model: Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
...
```

I'm not sure how we can handle this directly in virtualized infra like in AWS, since the metal3 API is not available there. I think we can resolve it indirectly via node-labels, where virtualized providers label nodes by `instance-type`. Then we can query the provider, or something like https://instaguide.io/ to get the exact `cpuinfo` per type...:

```yaml
kind: Node
apiVersion: v1
metadata:
  labels:
   ...
    node.kubernetes.io/instance-type: m5.2xlarge
    beta.kubernetes.io/instance-type: m5.2xlarge
```


I think engineering a custom controller to expose `cpuinfo` is a bad idea which is:
1. Ton of work to make right
2. Requires us to solve scheduling in a case of dynamic node counts etc.
3. Needs to respect node evictions due to clsuter upgrades/node reboots etc.

I think it's a lot of work to so something like https://github.com/operate-first/support/issues/409#issuecomment-934183242 and I would suggest not to do that.
