### ISSUE TITLE
[OSC cl2] Pods scheduled by kubeflow should be able to get GPU nodes

### ISSUE THREAD

**Issue by Shreyanand** [operate-first/support#568]
In the os-climate kubeflow namespace on the cl2 cluster, the pods spawned by the kubeflow pipelines can not match the nodes that have taints for GPUs. 
To be able to do so, either Elyra or kubeflow has to add toleration to the pod it generates ([upstream issue](https://github.com/elyra-ai/elyra/issues/2681)). 
While that gets addressed upstream, a temporary workaround should be found.

**Comment by redmikhail** [comment]
Preferred solution is if Elyra could pass podTemplate section to tekton pipelines https://tekton.dev/vault/pipelines-v0.14.3/podtemplates/ . Something similar to https://github.com/kubeflow/kfp-tekton/blob/b14f952ceb9c2c8b02f8b38298fa6264fac6b1dd/sdk/python/tests/compiler/testdata/node_selector_from_pipeline.yaml . As a temporary solution tolerations in podTemplates can be set for all pipelines https://tekton.dev/docs/pipelines/install/#customizing-basic-execution-parameters . Disadvantage of the latter approach is all pipelines , tasks will have thede tolerations

**Comment by redmikhail** [comment]
Following https://access.redhat.com/documentation/en-us/openshift_container_platform/4.9/html/cicd/pipelines#release-notes-1-6-2_op-release-notes document added toleration to TektonConfig in following form 
```
  config:
       tolerations:
        - effect: NoSchedule
          key: odh/notebook
          operator: Equal
          value: 'true'
        - effect: NoSchedule
          key: nvidia.com/gpu
          operator: Exists
```
While objects in openshift-pipelines namespace have received toleration , it appears change has no effect on kubeflow pipelines . As temporary workaround add tolerations on the whole kubeflow namespace (https://docs.openshift.com/container-platform/4.9/nodes/scheduling/nodes-scheduler-taints-tolerations.html#nodes-scheduler-taints-tolerations-projects_nodes-scheduler-taints-tolerations)
