### ISSUE TITLE
Request to add: ResourceQuota for `apicurio`

### ISSUE THREAD

**Issue by andreaTP** [operate-first/support#623]
### Team name

apicurio

### Explain why this resource is needed

We have two namespaces `apicurio-apicurio-registry` and `api-designer` and we are currently hitting resources limits(mainly CPU but MEM soon too).

```yaml
    limits.cpu: '4'
    limits.memory: 16Gi
    requests.cpu: '4'
    requests.memory: 16Gi
```

We started deploying multitenant configurations that require additional components and we run >= 3 JVMs components, this means that during rolling updates(involving also `DeploymentConfig`s lifecycle hooks and builders) of the entire infrastructure we are consuming much more than the provided 4 CPUs.

In addition, we plan to integrate more monitoring infrastructure in the near future.

### Resource(s) being requested

I'm asking a `ResourceQuota` increase for the 2 Namespaces to `apicurio-apicurio-registry` and `api-designer` to:

```yaml
kind: ResourceQuota
apiVersion: v1
metadata:
  name: large
spec:
  hard:
    ...
    limits.cpu: '32'
    limits.memory: 128Gi
    requests.cpu: '16'
    requests.memory: 64Gi
    ...
```
