### ISSUE TITLE
Syncing CRs and Operators in the right order

### ISSUE THREAD

**Issue by HumairAK** [operate-first/support#715]
When we have PR's where an operator is being added along with a CR, if ArgoCD decides to sync the CRs first, then it will fail the entire sync all together. One way around this is to use argocd [waves](https://argo-cd.readthedocs.io/en/stable/user-guide/sync-waves/). Where the manifests that need to be deployed first have the lower value. 

One issue with this solution is that when the operator sub is deployed, OLM still needs to install the CRDs before we can begin installing the CR, so argocd sync might _still_ fail, but if auto sync is on, it should keep trying and eventually succeed, which would be better than the current state anyway.

**Comment by durandom** [comment]
@HumairAK do we have `waves` installed? Is this still an issue? Can we close this otherwise?

/assign @HumairAK

**Comment by larsks** [comment]
This is still an issue and cannot be solved with sync waves. I have some thoughts, because we just ran into this on the NERC cluster. I will add them here shortly; making sure I am not a crazy person first.

**Comment by larsks** [comment]
Here's the essential problem:

ArgoCD [performs a dry-run](https://argo-cd.readthedocs.io/en/latest/user-guide/sync-options/#skip-dry-run-for-new-custom-resources-types) before applying an application's manifest in which it checks to make sure that any referenced resource kinds are either:

- Already available in the cluster, or
- Provided by the manifests being installed

When installing an operator via an OLM subscription, **these checks will always fail**. The CRDs provided by the operator are neither available in the cluster nor provided by the manifests, so the dry-run will fail and ArgoCD will not sync the application. You cannot resolve this via the sync waves mechanism; the dry-run happens before ArgoCD starts executing sync waves.

You can work around this problem by syncing individual resources (i.e. the operator subscriptions and any requirements, like namespaces and operatorgroups).

On a call with @HumairAK and @naved001 today, we talked about a few different solutions:

1. As documented in the above link, it's possible to exclude individual resources from the dry-run by applying a specific annotation. In https://github.com/OCP-on-NERC/nerc-ocp-config/pull/99 I adopted this solution (because it's expedient) by applying patches in the cluster-scope overlay, like this:

    ```
    - target:
        group: "external-secrets.io"
        name: ".*"
      patch: |
        - op: add
          path: /metadata/annotations/argocd.argoproj.io~1sync-options
          value: "SkipDryRunOnMissingResource=true"
    - target:
        group: "operator.external-secrets.io"
        name: ".*"
      patch: |
        - op: add
          path: /metadata/annotations/argocd.argoproj.io~1sync-options
          value: "SkipDryRunOnMissingResource=true"
    - target:
        group: "nmstate.io"
        name: ".*"
      patch: |
        - op: add
          path: /metadata/annotations/argocd.argoproj.io~1sync-options
          value: "SkipDryRunOnMissingResource=true"
    ```

    This applies the `argocd.argoproj.io/sync-options` annotation to manifests by API group.

    The problem with this solution is that it needs updating every time you introduce a new operator.

2. @HumairAK suggests that maybe we could just apply the annotation on *all* resources. That is:

    ```
    commonAnnotations:
      argocd.argoproj.io/sync-options: SkipDryRunOnMissingResources=true
    ```

    I'm going to ask around and see if there are any downsides to doing this . Presumably the dry-run stage exists for a reason; what would we be giving up if we used this solution?

3. An alternative solution would be to create a dedicated ArgoCD app for operator subscriptions (and their dependencies, like namespaces and operatorgroups). This would allow the operator subscriptions to succeed; once the installs were finished, other applications that depend on the CRDs would be able to sync.

  Conceptually this is my favorite solution, but there was some concern that it would introduce some confusion about how to handle some resources: we would have e.g. namespaces in both the "cluster-scope" application and in this hypothetical "operator-subscription" application.

My action item is to try to ask around on channels where argocd is on-topic to see (a) if there exists some sort of existing best practice for this issue, and (b) what might be the disadvantages to (2).
